# Generated by Django 6.0.4 on 2026-04-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
