# Generated by Django 6.0.4 on 2026-04-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
    ]
