# Generated by Django 6.0.4 on 2026-04-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_mensaje_archivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilnegocio',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
