# Generated by Django 6.0.4 on 2026-04-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_solicituddemo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddemo',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
