# Generated by Django 6.0.4 on 2026-04-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_alter_solicituddemo_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddemo',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
