# Generated by Django 6.0.4 on 2026-04-27 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_solicituddemo_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.perfilnegocio'),
        ),
    ]
