# Generated by Django 6.0.4 on 2026-04-27 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_reserva_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='reservas.perfilnegocio'),
        ),
    ]
