# Generated by Django 6.0.4 on 2026-04-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_servicio_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilnegocio',
            name='rubro',
            field=models.CharField(choices=[('deporte', '🏆 Deportes / Canchas'), ('belleza', '✂️ Belleza / Barbería'), ('salud', '🏥 Salud / Bienestar'), ('educacion', '📚 Educación / Clases'), ('comida', '🍽️ Comida / Restaurante'), ('eventos', '🎉 Eventos / Celebraciones'), ('spa', '💆 Spa / Relajación'), ('general', '📦 General / Otros')], default='general', max_length=20),
        ),
    ]
