# Generated by Django 6.0.4 on 2026-04-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_perfilnegocio_rubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilnegocio',
            name='instagram',
            field=models.CharField(blank=True, help_text='Usuario de Instagram (ej: turnoclic)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfilnegocio',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número de WhatsApp con código país (ej: 56912345678)', max_length=20, null=True),
        ),
    ]
