# Generated by Django 6.0.4 on 2026-04-29 01:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_perfilnegocio_instagram_perfilnegocio_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilnegocio',
            name='activo',
            field=models.BooleanField(default=False, help_text='Si el negocio está activo (demo aprobada)'),
        ),
        migrations.AddField(
            model_name='perfilnegocio',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, help_text='Fecha de expiración del demo', null=True),
        ),
        migrations.AddField(
            model_name='perfilnegocio',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha de solicitud demo'),
            preserve_default=False,
        ),
    ]
