# Generated by Django 6.0.4 on 2026-04-29 01:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_perfilnegocio_activo_perfilnegocio_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilnegocio',
            name='fecha_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de solicitud demo'),
        ),
    ]
