# Generated by Django 6.0.4 on 2026-05-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0014_alter_perfilnegocio_fecha_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
    ]
