# Generated by Django 6.0.4 on 2026-05-01 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_reserva_archivado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, '★☆☆☆☆ - Muy malo'), (2, '★★☆☆☆ - Malo'), (3, '★★★☆☆ - Regular'), (4, '★★★★☆ - Bueno'), (5, '★★★★★ - Excelente')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('publicada', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='reservas.cliente')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='reservas.perfilnegocio')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resena', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
